Repository NekoDar/Sirena, pull requests merged in 2022-12, with the labels that each got.

#1 Апдейт ReadMe
  README.md
Labels: No C#

#3 Свечи и автомат для будущих вещей
  Resources/Prototypes/ERP/VendingMachine/VendingMachineERP.yml
  Resources/Prototypes/ERP/candle/candle.yml
  Resources/Textures/ERP/VendingMachineERP.rsi/case.png
  Resources/Textures/ERP/VendingMachineERP.rsi/deny-unshaded.png
  Resources/Textures/ERP/VendingMachineERP.rsi/meta.json
  Resources/Textures/ERP/VendingMachineERP.rsi/off.png
  Resources/Textures/ERP/VendingMachineERP.rsi/panel.png
  Resources/Textures/ERP/VendingMachineERP.rsi/screen.png
  Resources/Textures/ERP/candle.rsi/candle_pink_lit.png
  Resources/Textures/ERP/candle.rsi/candle_pink_off.png
  Resources/Textures/ERP/candle.rsi/candle_teal_lit.png
  Resources/Textures/ERP/candle.rsi/candle_teal_off.png
  Resources/Textures/ERP/candle.rsi/meta.json
Labels: No C#, Changes: Sprites

#5 Update Rules.txt
  Resources/Server Info/Rules.txt
Labels: No C#, Status: Needs Review

#7 sponsorOnly: false
  Resources/Prototypes/Corvax/Entities/Mobs/Customization/Markings/cat_parts.yml
  Resources/Prototypes/Corvax/Entities/Mobs/Customization/Markings/fox_parts.yml
  Resources/Prototypes/Corvax/Entities/Mobs/Customization/Markings/sponsor.yml
  Resources/Prototypes/Corvax/Mobs/Customization/Markings/cat_parts.yml
  Resources/Prototypes/Corvax/Mobs/Customization/Markings/human_hair.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/cat_parts.yml
Labels: No C#

#9 Update README.md
  README.md
Labels: No C#
